blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/4-b100m/system-governance-framework/discussions
    about: Please ask and answer questions here.
